version: 2.1
jobs:
  create_infrastructure: 
      docker: 
        - image: circleci/node:13.8.0
      steps:
        - checkout 
        - run: echo "hello world" 
workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires:
             - create_infrastructure
create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --region us-east-2

configure_infrastructure: 
  docker:
    - image: python:3.7-alpine3.11
  steps:
    - checkout
    - add_ssh_keys:
            fingerprints: ["88:7a:4c:33:ee:fe:65:d4:72:d0:e5:48:be:d1:c7:ef"] 
    - run:
        name: Install dependacies
        command: |
          apk add --update ansible
    - run:
        name: Configure server
        command: |
          ansible-playbook -i inventory.txt playbook.yml


